'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Status
    
    '''<summary>
    '''UpdateTimer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdateTimer As Global.System.Web.UI.Timer
    
    '''<summary>
    '''StatusPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusPanel As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''JumbrotronBG control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents JumbrotronBG As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''JumboStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents JumboStatus As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''JumboSubtext control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents JumboSubtext As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ExternalPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ExternalPanel As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''ServersPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ServersPanel As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''InternalPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents InternalPanel As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''TimeLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TimeLabel As Global.System.Web.UI.WebControls.Label
End Class
